---
title: "Sliding Windows Analysis"
subtitle: "Weird Populations, Size 50kb step 10kb"
output: html_notebook
---

```{r libraries, echo = FALSE}
library(tidyverse)
library(ggtext)
```

```{r data_org, echo = FALSE}
cols <- c("region", 
          "chr", 
          "midPos", 
          "Nsites", 
          "Fst")


### East Grand Lake vs Lake Champlain ###
EGL_LkC <- read_delim("data/sliding_window_fst_weirdos/EGL--x--LkC--size-50000--step-10000.tsv", 
                    skip = 2, 
                    delim = "\t", 
                    col_names = cols,
                    show_col_types = FALSE)
EGL_LkC_cum <- EGL_LkC %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

EGL_LkC <- EGL_LkC %>%
  inner_join(EGL_LkC_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

EGL_LkC_axis_set <- EGL_LkC %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))

### East Grand Lake vs Pattagansett Lake ###
EGL_PtL <- read_delim("data/sliding_window_fst_weirdos/EGL--x--PtL--size-50000--step-10000.tsv", 
                    skip = 2, 
                    delim = "\t", 
                    col_names = cols,
                    show_col_types = FALSE)
EGL_PtL_cum <- EGL_PtL %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

EGL_PtL <- EGL_PtL %>%
  inner_join(EGL_PtL_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

EGL_PtL_axis_set <- EGL_PtL %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))

### East Grand Lake vs Quonnipaug Lake ###
EGL_QnL <- read_delim("data/sliding_window_fst_weirdos/EGL--x--QnL--size-50000--step-10000.tsv", 
                    skip = 2, 
                    delim = "\t", 
                    col_names = cols,
                    show_col_types = FALSE)
EGL_QnL_cum <- EGL_QnL %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

EGL_QnL <- EGL_QnL %>%
  inner_join(EGL_QnL_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

EGL_QnL_axis_set <- EGL_QnL %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))

### East Grand Lake vs Rogers Lake ###
EGL_RgL <- read_delim("data/sliding_window_fst_weirdos/EGL--x--RgL--size-50000--step-10000.tsv", 
                    skip = 2, 
                    delim = "\t", 
                    col_names = cols,
                    show_col_types = FALSE)
EGL_RgL_cum <- EGL_RgL %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

EGL_RgL <- EGL_RgL %>%
  inner_join(EGL_RgL_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

EGL_RgL_axis_set <- EGL_RgL %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))

### East Grand Lake vs Roanoke River ###
EGL_RnR <- read_delim("data/sliding_window_fst_weirdos/EGL--x--RnR--size-50000--step-10000.tsv", 
                    skip = 2, 
                    delim = "\t", 
                    col_names = cols,
                    show_col_types = FALSE)
EGL_RnR_cum <- EGL_RnR %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

EGL_RnR <- EGL_RnR %>%
  inner_join(EGL_RnR_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

EGL_RnR_axis_set <- EGL_RnR %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))

### Pattagansett Lake vs Quonnipaug Lake ###
PtL_QnL <- read_delim("data/sliding_window_fst_weirdos/PtL--x--QnL--size-50000--step-10000.tsv", 
                    skip = 2, 
                    delim = "\t", 
                    col_names = cols,
                    show_col_types = FALSE)
PtL_QnL_cum <- PtL_QnL %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

PtL_QnL <- PtL_QnL %>%
  inner_join(PtL_QnL_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

PtL_QnL_axis_set <- PtL_QnL %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))

### Pattagansett Lake vs Rogers Lake ###
PtL_RgL <- read_delim("data/sliding_window_fst_weirdos/PtL--x--RgL--size-50000--step-10000.tsv", 
                    skip = 2, 
                    delim = "\t", 
                    col_names = cols,
                    show_col_types = FALSE)
PtL_RgL_cum <- PtL_RgL %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

PtL_RgL <- PtL_RgL %>%
  inner_join(PtL_RgL_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

PtL_RgL_axis_set <- PtL_RgL %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))

### Rogers Lake vs Quonnipaug Lake ###
RgL_QnL <- read_delim("data/sliding_window_fst_weirdos/RgL--x--QnL--size-50000--step-10000.tsv", 
                    skip = 2, 
                    delim = "\t", 
                    col_names = cols,
                    show_col_types = FALSE)
RgL_QnL_cum <- RgL_QnL %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

RgL_QnL <- RgL_QnL %>%
  inner_join(RgL_QnL_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

RgL_QnL_axis_set <- RgL_QnL %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))

### Roanoke River vs Lake Champlain ###
RnR_LkC <- read_delim("data/sliding_window_fst_weirdos/RnR--x--LkC--size-50000--step-10000.tsv", 
                    skip = 2, 
                    delim = "\t", 
                    col_names = cols,
                    show_col_types = FALSE)
RnR_LkC_cum <- RnR_LkC %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

RnR_LkC <- RnR_LkC %>%
  inner_join(RnR_LkC_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

RnR_LkC_axis_set <- RnR_LkC %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))

### Roanoke River vs Pattagansett Lake ###
RnR_PtL <- read_delim("data/sliding_window_fst_weirdos/RnR--x--PtL--size-50000--step-10000.tsv",
                    skip = 2,
                    delim = "\t",
                    col_names = cols,
                    show_col_types = FALSE)
RnR_PtL_cum <- RnR_PtL %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

RnR_PtL <- RnR_PtL %>%
  inner_join(RnR_PtL_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

RnR_PtL_axis_set <- RnR_PtL %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))

### Roanoke River vs Quonnipaug Lake ###
RnR_QnL <- read_delim("data/sliding_window_fst_weirdos/RnR--x--QnL--size-50000--step-10000.tsv",
                    skip = 2,
                    delim = "\t",
                    col_names = cols,
                    show_col_types = FALSE)
RnR_QnL_cum <- RnR_QnL %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

RnR_QnL <- RnR_QnL %>%
  inner_join(RnR_QnL_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

RnR_QnL_axis_set <- RnR_QnL %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))

### Roanoke River vs Rogers Lake ###
RnR_RgL <- read_delim("data/sliding_window_fst_weirdos/RnR--x--RgL--size-50000--step-10000.tsv",
                    skip = 2,
                    delim = "\t",
                    col_names = cols,
                    show_col_types = FALSE)
RnR_RgL_cum <- RnR_RgL %>%
  group_by(chr) %>%
  summarise(max_pos = max(midPos)) %>%
  mutate(pos_add = lag(cumsum(max_pos), default = 0)) %>%
  select(chr, pos_add)

RnR_RgL <- RnR_RgL %>%
  inner_join(RnR_RgL_cum, by = "chr") %>%
  mutate(pos_cum = midPos + pos_add)

RnR_RgL_axis_set <- RnR_RgL %>%
  group_by(chr) %>%
  summarise(center = mean(pos_cum))
```


```{r EGL_x_LkC}
EGL_LkC_plot <- ggplot(data = EGL_LkC, 
                       mapping = aes(x = pos_cum, 
                                     y = Fst, 
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = EGL_LkC_axis_set$chr, 
                     breaks = EGL_LkC_axis_set$center) +
  scale_y_continuous(expand = c(0,0), 
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"), 
                                  unique(length(EGL_LkC_axis_set$chr)))) +
  labs(x = NULL, 
       y = "Fst", 
       title = "East Grand L. vs L. Champlain", 
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
EGL_LkC_plot

```


```{r EGL_x_PtL}
EGL_PtL_plot <- ggplot(data = EGL_PtL, 
                       mapping = aes(x = pos_cum, 
                                     y = Fst, 
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = EGL_PtL_axis_set$chr, 
                     breaks = EGL_PtL_axis_set$center) +
  scale_y_continuous(expand = c(0,0), 
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"), 
                                  unique(length(EGL_PtL_axis_set$chr)))) +
  labs(x = NULL, 
       y = "Fst", 
       title = "East Grand L. vs Pattagansett L.", 
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
EGL_PtL_plot

```

```{r EGL_x_QnL}
EGL_QnL_plot <- ggplot(data = EGL_QnL, 
                       mapping = aes(x = pos_cum, 
                                     y = Fst, 
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = EGL_QnL_axis_set$chr, 
                     breaks = EGL_QnL_axis_set$center) +
  scale_y_continuous(expand = c(0,0), 
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"), 
                                  unique(length(EGL_QnL_axis_set$chr)))) +
  labs(x = NULL, 
       y = "Fst", 
       title = "East Grand L. vs Quonnipaug L.", 
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
EGL_QnL_plot

```

```{r EGL_x_RgL}
EGL_RgL_plot <- ggplot(data = EGL_RgL, 
                       mapping = aes(x = pos_cum, 
                                     y = Fst, 
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = EGL_RgL_axis_set$chr, 
                     breaks = EGL_RgL_axis_set$center) +
  scale_y_continuous(expand = c(0,0), 
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"), 
                                  unique(length(EGL_RgL_axis_set$chr)))) +
  labs(x = NULL, 
       y = "Fst", 
       title = "East Grand L. vs Rogers L.", 
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
EGL_RgL_plot

```

```{r EGL_x_RnR}
EGL_RnR_plot <- ggplot(data = EGL_RnR, 
                       mapping = aes(x = pos_cum, 
                                     y = Fst, 
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = EGL_RnR_axis_set$chr, 
                     breaks = EGL_RnR_axis_set$center) +
  scale_y_continuous(expand = c(0,0), 
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"), 
                                  unique(length(EGL_RnR_axis_set$chr)))) +
  labs(x = NULL, 
       y = "Fst", 
       title = "East Grand L. vs Roanoke R.", 
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
EGL_RnR_plot

```

```{r PtL_x_QnL}
PtL_QnL_plot <- ggplot(data = PtL_QnL, 
                       mapping = aes(x = pos_cum, 
                                     y = Fst, 
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = PtL_QnL_axis_set$chr, 
                     breaks = PtL_QnL_axis_set$center) +
  scale_y_continuous(expand = c(0,0), 
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"), 
                                  unique(length(PtL_QnL_axis_set$chr)))) +
  labs(x = NULL, 
       y = "Fst", 
       title = "Pattagansett L. vs Quonnipaug L.", 
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
PtL_QnL_plot

```

```{r PtL_x_RgL}
PtL_RgL_plot <- ggplot(data = PtL_RgL, 
                       mapping = aes(x = pos_cum, 
                                     y = Fst, 
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = PtL_RgL_axis_set$chr, 
                     breaks = PtL_RgL_axis_set$center) +
  scale_y_continuous(expand = c(0,0), 
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"), 
                                  unique(length(PtL_RgL_axis_set$chr)))) +
  labs(x = NULL, 
       y = "Fst", 
       title = "Pattagansett L. vs Rogers L.", 
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
PtL_RgL_plot

```

```{r RgL_x_QnL}
RgL_QnL_plot <- ggplot(data = RgL_QnL, 
                       mapping = aes(x = pos_cum, 
                                     y = Fst, 
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = RgL_QnL_axis_set$chr, 
                     breaks = RgL_QnL_axis_set$center) +
  scale_y_continuous(expand = c(0,0), 
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"), 
                                  unique(length(RgL_QnL_axis_set$chr)))) +
  labs(x = NULL, 
       y = "Fst", 
       title = "Rogers L. vs Quonnipaug L.", 
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
RgL_QnL_plot

```

```{r RnR_x_LkC}
RnR_LkC_plot <- ggplot(data = RnR_LkC, 
                       mapping = aes(x = pos_cum, 
                                     y = Fst, 
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = RnR_LkC_axis_set$chr, 
                     breaks = RnR_LkC_axis_set$center) +
  scale_y_continuous(expand = c(0,0), 
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"), 
                                  unique(length(RnR_LkC_axis_set$chr)))) +
  labs(x = NULL, 
       y = "Fst", 
       title = "Roanoke R. vs L. Champlain", 
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
RnR_LkC_plot

```

```{r RnR_x_PtL}
RnR_PtL_plot <- ggplot(data = RnR_PtL,
                       mapping = aes(x = pos_cum,
                                     y = Fst,
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = RnR_PtL_axis_set$chr,
                     breaks = RnR_PtL_axis_set$center) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"),
                                  unique(length(RnR_PtL_axis_set$chr)))) +
  labs(x = NULL,
       y = "Fst",
       title = "Roanoke R. vs Pattagansett L.",
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
RnR_PtL_plot

```

```{r RnR_x_QnL}
RnR_QnL_plot <- ggplot(data = RnR_QnL,
                       mapping = aes(x = pos_cum,
                                     y = Fst,
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = RnR_QnL_axis_set$chr,
                     breaks = RnR_QnL_axis_set$center) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"),
                                  unique(length(RnR_QnL_axis_set$chr)))) +
  labs(x = NULL,
       y = "Fst",
       title = "Roanoke R. vs Quonnipaug L.",
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
RnR_QnL_plot

```

```{r RnR_x_RgL}
RnR_RgL_plot <- ggplot(data = RnR_RgL,
                       mapping = aes(x = pos_cum,
                                     y = Fst,
                                     color = as_factor(chr))) +
  geom_point(alpha = 0.75, size = 0.5) +
  scale_x_continuous(label = RnR_RgL_axis_set$chr,
                     breaks = RnR_RgL_axis_set$center) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(-0.05, 1)) +
  scale_color_manual(values = rep(c("#242b35", "#869ca8"),
                                  unique(length(RnR_RgL_axis_set$chr)))) +
  labs(x = NULL,
       y = "Fst",
       title = "Roanoke R. vs Rogers L.",
       subtitle = "Size 50,000 Step 10,000") +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.title.y = element_markdown(),
        axis.text.x = element_text(angle = 90,
                                  size = 8,
                                  vjust = 0.5))
RnR_RgL_plot

```

```{r saving_plots, eval = FALSE}
### Using ggsave to save the manhattan plots, or as I will now refer to it: ###
# Saving Private Plots (Ryan lol) ##
ggsave("figures/sliding-windows-fst/MIDA-x-NATLA-sz50-chrom19-spike.png", 
       plot = mxn50_chr19_spike_plot, 
       width = 10, 
       height = 4)
```




